import { Injectable, signal } from '@angular/core';
import { scopedKey } from '../../account-scope';
import { DEFAULT_SPLIT_MODE, SplitMode, SPLIT_MODES } from './split-modes';

const WORKSPACE_KEY_BASE = 'mockingbird_write_workspace';

/** Where a draft sits on the board. Written by the kanban sprint, read here. */
export type WriteColumn = 'ideas' | 'writing' | 'editing' | 'scheduled';

const COLUMNS: readonly WriteColumn[] = ['ideas', 'writing', 'editing', 'scheduled'];

/**
 * Workspace metadata for one draft — the things the writing surface needs to
 * remember that no draft *kind* has anywhere to put.
 *
 * Three of the four kinds live on a server with no field for any of this, so it
 * cannot live on the draft. It is a sidecar keyed by {@link DraftItem.key},
 * which is the only identifier unique across kinds.
 */
export interface WriteMeta {
  splitMode: SplitMode;
  /**
   * The kanban column. Optional and unwritten in this sprint — the shape exists
   * now so the board sprint adds a writer rather than a migration.
   */
  column?: WriteColumn;
}

type WorkspaceRecord = Record<string, WriteMeta>;

/**
 * Per-draft workspace preferences, account-scoped in localStorage.
 *
 * This is a cache of preferences, not user content: every entry can be
 * regenerated by asking the user again, and losing one costs a click. That is
 * why unknown fields are dropped rather than preserved, why a malformed record
 * resets instead of throwing, and why entries for drafts that no longer exist
 * are pruned on demand. Treating it as precious would mean carrying migration
 * code for something nobody would miss.
 */
@Injectable({ providedIn: 'root' })
export class WriteWorkspace {
  private readonly record = signal<WorkspaceRecord>(load());

  /** This draft's metadata, with defaults filled in. Never null. */
  meta(key: string): WriteMeta {
    return this.record()[key] ?? { splitMode: DEFAULT_SPLIT_MODE };
  }

  splitMode(key: string): SplitMode {
    return this.meta(key).splitMode;
  }

  setSplitMode(key: string, mode: SplitMode): void {
    this.patch(key, { splitMode: mode });
  }

  column(key: string): WriteColumn | undefined {
    return this.meta(key).column;
  }

  setColumn(key: string, column: WriteColumn): void {
    this.patch(key, { column });
  }

  /**
   * Drop entries whose draft is gone.
   *
   * Called with the keys that currently exist rather than on a timer: the
   * workspace has no way to know a draft was deleted, and a sidecar that grows
   * forever eventually costs more than the preferences it holds are worth.
   */
  prune(liveKeys: Iterable<string>): void {
    const live = new Set(liveKeys);
    const current = this.record();
    const kept: WorkspaceRecord = {};
    let dropped = false;
    for (const [key, meta] of Object.entries(current)) {
      if (live.has(key)) {
        kept[key] = meta;
      } else {
        dropped = true;
      }
    }
    if (dropped) {
      this.record.set(kept);
      persist(kept);
    }
  }

  /** Forget one draft's metadata, when that draft is deleted from the workspace. */
  forget(key: string): void {
    const current = this.record();
    if (!(key in current)) {
      return;
    }
    const next = { ...current };
    delete next[key];
    this.record.set(next);
    persist(next);
  }

  private patch(key: string, changes: Partial<WriteMeta>): void {
    const next = { ...this.record(), [key]: { ...this.meta(key), ...changes } };
    this.record.set(next);
    persist(next);
  }
}

/**
 * Read the stored record, keeping only what this version understands.
 *
 * A stored entry with an unrecognized split mode (an older or newer build, or a
 * hand-edited value) falls back to the default rather than being dropped, so the
 * draft's column survives a mode this build has never heard of.
 */
function load(): WorkspaceRecord {
  let raw: string | null;
  try {
    raw = localStorage.getItem(scopedKey(WORKSPACE_KEY_BASE));
  } catch {
    return {};
  }
  if (!raw) {
    return {};
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {};
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return {};
  }
  const record: WorkspaceRecord = {};
  for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
    if (!value || typeof value !== 'object') {
      continue;
    }
    const entry = value as Partial<WriteMeta>;
    const splitMode = SPLIT_MODES.includes(entry.splitMode as SplitMode)
      ? (entry.splitMode as SplitMode)
      : DEFAULT_SPLIT_MODE;
    const meta: WriteMeta = { splitMode };
    if (COLUMNS.includes(entry.column as WriteColumn)) {
      meta.column = entry.column as WriteColumn;
    }
    record[key] = meta;
  }
  return record;
}

function persist(record: WorkspaceRecord): void {
  try {
    localStorage.setItem(scopedKey(WORKSPACE_KEY_BASE), JSON.stringify(record));
  } catch {
    // Storage full or unavailable — preferences degrade to session-only, which
    // is the right failure for a cache of preferences.
  }
}
